### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chupinmaxime** [thruston/Drawing-with-Metapost#1]
Hello,

I am going through the issues because I did not find any other way to contact you. 

I think your documents are wonderful!

With the French TeX users group (GUTenberg https://www.gutenberg-asso.fr), we have set up a site to illustrate the use of MetaPost with examples:

https://metapost.gutenberg-asso.fr

I wanted to know if you would agree to let me publish some of your productions there (with reference and credit of course). 

All the best,

Maxime Chupin

**Comment by thruston** [comment]
Thanks for the comments.   Je vous répondrai par mail prochainement.
